import type { Metadata } from "next";
import { PublicHero, PublicPageShell } from "@/components/public-page-shell";
import { VehicleSubmissionForm } from "./vehicle-submission-form";

export const metadata: Metadata = { title: "Submit a Car | Motorcar Society", description: "Privately submit a significant collector car for Motorcar Society review." };

export default function SubmitCarPage() {
  return <PublicPageShell><main><PublicHero eyebrow="Submit a Car" title="Every important car begins with a conversation." intro="Share the essentials with us privately. A submission does not publish the car or create a Registry listing; Barnaby reviews it personally first." /><section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto grid max-w-[90rem] gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><aside><p className="eyebrow">What happens next</p><ol className="mt-7 space-y-6">{[["01","Tell us about the car","Provide the basic identity, location and story."],["02","Private review","Barnaby will contact you to understand the car and available records."],["03","Build the file","If accepted, photographs and provenance are organized into a private vehicle file."],["04","Approve any release","Nothing is published until the presentation and audience are approved."]].map(([number,title,copy]) => <li key={number} className="flex gap-4"><span className="font-display text-2xl text-[var(--gold-light)]">{number}</span><span><strong className="block text-white">{title}</strong><span className="mt-1 block text-sm leading-6 text-white/48">{copy}</span></span></li>)}</ol><div className="mt-10 border-t border-white/10 pt-7 text-sm leading-6 text-white/48"><p>Prefer to speak directly?</p><a href="tel:+16195182469" className="mt-2 block text-lg font-semibold text-[var(--gold-light)]">619-518-2469</a><a href="mailto:bbforcars@gmail.com" className="mt-1 block text-[var(--gold-light)]">bbforcars@gmail.com</a></div></aside><VehicleSubmissionForm /></div></section></main></PublicPageShell>;
}
