import Link from "next/link";
import { PublicHero, PublicPageShell } from "@/components/public-page-shell";

const tiers = [
  { name: "Verified Member", price: "Complimentary at launch", description: "For collectors who want trusted access to the Registry and a private place to record the cars they are actively seeking.", benefits: ["Approved access to member Registry releases", "A private, editable Wanted List", "Private dossier requests", "Thoughtful introductions when a relevant car appears"] },
  { name: "Priority Member", price: "$995 annually", description: "For active collectors who want earlier attention when opportunities align with their interests.", benefits: ["Everything included with Verified Membership", "Earlier consideration for relevant private matches", "Direct specialist coordination", "Priority follow-up on dossier requests"] },
  { name: "Private Client", price: "$2,500 annually", description: "Invitation-only support for collectors seeking a more personal acquisition and collection relationship.", benefits: ["Everything included with Priority Membership", "Personal acquisition support", "Collection-level planning and discreet sourcing", "Invitation-only introductions and coordination"] },
];

export default function AboutPage() {
  return <PublicPageShell><main><PublicHero eyebrow="About the Society" title="A better home for important cars and the people who preserve them." intro="Motorcar Society is a private collector community built around provenance, discretion and relationships—not crowded public listings." />
    <section className="bg-[#e9e5dc] px-5 py-16 text-[#171918] sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto grid max-w-[90rem] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806c49]">Why we exist</p><h2 className="mt-5 font-display text-5xl leading-[.96] sm:text-6xl">The story should stay with the car.</h2></div><div className="space-y-6 text-lg leading-8 text-black/62"><p>Exceptional motorcars are more than specifications and photographs. Their identity, ownership, restoration and care form a history worth protecting.</p><p>The Registry keeps that material organized, helps qualified collectors understand a car properly and allows introductions to happen privately. A member Wanted List also helps us recognize the right collector before a car is broadly offered.</p><p>Every application is reviewed by the Motorcar Society team. Approval, access and membership level are assigned personally.</p></div></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-[90rem]"><p className="eyebrow">Membership</p><h2 className="mt-4 max-w-3xl font-display text-5xl leading-tight">Choose the relationship that fits how you collect.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{tiers.map((tier) => <article key={tier.name} className="rounded-2xl border border-white/10 bg-[#181a19] p-7"><h3 className="font-display text-3xl">{tier.name}</h3><p className="mt-3 font-semibold text-[var(--gold-light)]">{tier.price}</p><p className="mt-5 leading-7 text-white/58">{tier.description}</p><ul className="mt-6 space-y-3 border-t border-white/10 pt-6 text-sm leading-6 text-white/65">{tier.benefits.map((benefit) => <li key={benefit} className="flex gap-3"><span className="text-[var(--gold-light)]">•</span>{benefit}</li>)}</ul></article>)}</div><p className="mt-7 max-w-3xl text-sm leading-6 text-white/45">Membership prices and availability are subject to confirmation during review. Motorcar Society may adjust access to protect member privacy and the confidentiality of vehicle information.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signin?mode=register" className="inline-flex min-h-14 items-center justify-center rounded-lg bg-[var(--gold)] px-7 font-semibold text-[#111]">Request membership</Link><Link href="/submit-a-car" className="inline-flex min-h-14 items-center justify-center rounded-lg border border-white/20 px-7 font-semibold">Submit a car</Link></div></div></section>
  </main></PublicPageShell>;
}
