import { ProseSection, PublicHero, PublicPageShell } from "@/components/public-page-shell";

export default function TermsPage() {
  return <PublicPageShell><main><PublicHero eyebrow="Terms" title="Terms for a trusted private community." intro="These terms protect the confidentiality, integrity and appropriate use of Motorcar Society and its Registry." /><ProseSection>
    <p><strong className="text-white">Effective September 6, 2026.</strong> By using Motorcar Society, you agree to these terms. If you do not agree, do not use the service.</p>
    <h2>Membership and access</h2><p>Creating an account does not guarantee membership. Applications are reviewed individually, and Motorcar Society may approve, limit, suspend or end access when reasonably necessary to protect members, owners, vehicle information or the service. You are responsible for your account and for keeping sign-in information confidential.</p>
    <h2>Private and confidential information</h2><p>You may use Registry information only for legitimate personal collecting and evaluation purposes. You may not republish, scrape, sell, distribute or misuse private listings, member information, source documents or dossier material. Sharing a permitted vehicle link does not grant the recipient automatic access.</p>
    <h2>Vehicle information and guidance</h2><p>Owners and contributors are responsible for the accuracy and authority of material they submit. Motorcar Society may organize or summarize that material but does not guarantee completeness, authenticity, condition, title, ownership or legal eligibility. Price guidance is informational and is not a certified appraisal, offer, promise of sale or financial advice.</p>
    <h2>No transaction guarantee</h2><p>Motorcar Society facilitates private information and introductions. Unless separately agreed in writing, it is not a party to a purchase agreement and does not guarantee that a vehicle will be offered, sold, purchased or delivered. Members should conduct independent inspections, title checks, legal review and due diligence.</p>
    <h2>Acceptable use</h2><p>You may not interfere with the service, attempt unauthorized access, upload unlawful or malicious material, impersonate another person, or use information to harass, spam or mislead others.</p>
    <h2>Intellectual property</h2><p>The Motorcar Society name, design and original site content are protected. Vehicle owners retain rights they hold in submitted material while granting Motorcar Society permission to store, process and display it as needed to provide the requested Registry services.</p>
    <h2>Availability and liability</h2><p>The service is provided on an “as available” basis. To the extent permitted by law, Motorcar Society is not responsible for indirect or consequential loss arising from use of the service, reliance on vehicle information or dealings between users.</p>
    <h2>Changes and contact</h2><p>These terms may be updated as the service develops. Material changes will be reflected by a revised effective date. Questions may be sent to <a href="mailto:bbforcars@gmail.com">bbforcars@gmail.com</a> or discussed at <a href="tel:+16195182469">619-518-2469</a>.</p>
  </ProseSection></main></PublicPageShell>;
}
